version: '3'
services:
  app:
    container_name: crm-api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "yarn dev"
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - crm-network

  # db:
  #   image: zcube/bitnami-compat-mongodb:latest
  #   container_name: crm-db
  #   restart: always
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - db-data:/bitnami/mongodb
  #   ports:
  #     - 27343:27017
  #   networks:
  #     - crm-network

  # redis:
  #   image: redis:latest
  #   container_name: crm-redis
  #   restart: always
  #   ports:
  #     - '6343:6379'
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - crm-network

networks:
  crm-network:

volumes:
  db-data:
  redis-data:
